services:
  web:
    env_file:
      - .env.example
      - .env.local
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3010}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3011}
      NODE_ENV: production
